name: Sonarcloud Coverage

on:
    workflow_dispatch:

jobs:

  build:
    name: Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Get Dependencies
        run: go get -v -t -d ./..
  
      - name: Run Unit Tests
        run: go test -timeout 10m -coverprofile=./cov.out ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt=sonarqube -out report.json ./...'

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
